config/routes.rb
Rails.application.routes.draw do
  
  resources :collections do 
    resources :receipes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :receipes
end

app/models/receipe.rb
class Receipe < ApplicationRecord
  belongs_to :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @receipes = Receipe.where("collection_id = ?", @collection.id)
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:category_name, :image_url)
    end
end

app/controllers/receipes_controller.rb
class ReceipesController < ApplicationController
  before_action :set_receipe, only: [:show, :edit, :update, :destroy]
  before_action :set_collection

  # GET /receipes
  # GET /receipes.json
  def index
    if params[:collection_id] != nil
      @receipes = Receipe.where(collection_id: params[:collection_id])
    else
      @receipes = Receipe.all
    end
    

    # @receipes = Receipe.all
    # raise
  end

  # GET /receipes/1
  # GET /receipes/1.json
  def show
  end

  # GET /receipes/new
  def new
    @receipe = Receipe.new
  end

  # GET /receipes/1/edit
  def edit
  end

  # POST /receipes
  # POST /receipes.json
  def create
    @receipe = Receipe.new(receipe_params)
    @receipe.collection_id = @collection.id

    respond_to do |format|
      if @receipe.save
        format.html { redirect_to collection_receipe_path(@collection,@receipe), notice: 'Receipe was successfully created.' }
        format.json { render :show, status: :created, location: @receipe }
      else
        format.html { render :new }
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipes/1
  # PATCH/PUT /receipes/1.json
  def update
    respond_to do |format|
      if @receipe.update(receipe_params)
        format.html { redirect_to collection_receipe_path(@collection,@receipe), notice: 'Receipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipe }
      else
        format.html { render :edit }
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipes/1
  # DELETE /receipes/1.json
  def destroy
    @receipe.destroy
    respond_to do |format|
      format.html { redirect_to collection_receipes_path(@collection), notice: 'Receipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipe
      @receipe = Receipe.find(params[:id])
    end

    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipe_params
      params.require(:receipe).permit(:receipe_name, :image_url, :prep_time_minutes, :cooking_time_minutes, :difficulty_level, :servings, :ingredients, :how_to_cook, :collection_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/receipes_helper.rb
module ReceipesHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_area :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.category_name %></td>  
        <td><%= collection.image_url %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @collection.category_name %>
</p>

<p>
  <strong>Receipes:</strong><br>
  <% @receipes.each do |receipe| %>
  #######################################
    <ul>
      <li>
        <h4>Receipe name</h4><%= receipe.receipe_name %>
      </li>
      <li>
        <h4>Difficulty Level</h4><%= receipe.difficulty_level %>
      </li>
    </ul>
      
    
  <% end %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Receipes', collection_receipes_path(@collection) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyColesReceipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receipes/_form.html.erb
<%= form_with(model: [@collection,receipe], local: true) do |form| %>
  <% if receipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipe.errors.count, "error") %> prohibited this receipe from being saved:</h2>

      <ul>
      <% receipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :receipe_name %>
    <%= form.text_field :receipe_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_area :image_url %>
  </div>

  <div class="field">
    <%= form.label :prep_time_minutes %>
    <%= form.number_field :prep_time_minutes %>
  </div>

  <div class="field">
    <%= form.label :cooking_time_minutes %>
    <%= form.number_field :cooking_time_minutes %>
  </div>

  <div class="field">
    <%= form.label :difficulty_level %>
    <%= form.text_field :difficulty_level %>
  </div>

  <div class="field">
    <%= form.label :servings %>
    <%= form.number_field :servings %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :how_to_cook %>
    <%= form.text_area :how_to_cook %>
  </div>

  <div class="field">
    <%= form.label :collection_id %>
    <%= form.select :collection_id, options_for_select(Collection.all.collect { |u| [u.category_name,u.id]}, :selected => receipe.collection_id) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipes/edit.html.erb
<h1>Editing Receipe</h1>

<%= render 'form', collection: @collection, receipe: @receipe  %>

<%= link_to 'Show', collection_receipe_path(@collection,@receipe) %> |
<%= link_to 'Back', collection_receipes_path(@collection) %>

app/views/receipes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Receipes</h1>

<table>
  <thead>
    <tr>
      <th>Receipe name</th>
      <th>Image url</th>
      <th>Prep time minutes</th>
      <th>Cooking time minutes</th>
      <th>Difficulty level</th>
      <th>Servings</th>
      <th>Ingredients</th>
      <th>How to cook</th>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipes.each do |receipe| %>
      <tr>
        <td><%= receipe.receipe_name %></td>
        <td><%= receipe.image_url %></td>
        <td><%= receipe.prep_time_minutes %></td>
        <td><%= receipe.cooking_time_minutes %></td>
        <td><%= receipe.difficulty_level %></td>
        <td><%= receipe.servings %></td>
        <td><%= receipe.ingredients %></td>
        <td><%= receipe.how_to_cook %></td>
        <td><%= receipe.collection ? receipe.collection.category_name : "" %></td>
        <td><%= link_to 'Show', collection_receipe_path(@collection, receipe) %></td>
        <td><%= link_to 'Edit', edit_collection_receipe_path(@collection, receipe) %></td>
        <td><%= link_to 'Destroy', collection_receipe_path(@collection, receipe), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipe', new_collection_receipe_path %>

app/views/receipes/new.html.erb
<h1>New Receipe</h1>

<%= render 'form', collection: @collection, receipe: @receipe %>

<%= link_to 'Back', collection_receipes_path(@collection) %>

app/views/receipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Receipe name:</strong>
  <%= @receipe.receipe_name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @receipe.image_url %>
</p>

<p>
  <strong>Prep time minutes:</strong>
  <%= @receipe.prep_time_minutes %>
</p>

<p>
  <strong>Cooking time minutes:</strong>
  <%= @receipe.cooking_time_minutes %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @receipe.difficulty_level %>
</p>

<p>
  <strong>Servings:</strong>
  <%= @receipe.servings %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @receipe.ingredients %>
</p>

<p>
  <strong>How to cook:</strong>
  <%= @receipe.how_to_cook %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @receipe.collection.category_name %>
</p>

<%= link_to 'Edit', edit_collection_receipe_path(@collection,@receipe) %> |
<%= link_to 'Back', collection_receipes_path(@collection) %>